name: Build & Publish DMGs via Spec

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64, x86_64]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Rosetta (for Intel)
        if: matrix.arch == 'x86_64'
        run: softwareupdate --install-rosetta --agree-to-license

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: ${{ matrix.arch == 'x86_64' && 'x64' || 'arm64' }}
      
      
      - name: Prepare & build in clean tmp
        run: |
            # 1) Make a brand-new empty dir
            TMP=$(mktemp -d)
            cd "$TMP"
  
            # 2) Create & activate a fresh venv in there
            python -m venv venv
            source venv/bin/activate
  
            # 3) Install exactly what we need (including NumPy)
            pip install --upgrade pip pyinstaller numpy
  
            # 4) Invoke PyInstaller on your spec (which lives in the repo)
            if [ "${{ matrix.arch }}" = "x86_64" ]; then
              # run under Rosetta and use module form so we never hit a local numpy/
              arch -x86_64 python -m PyInstaller --clean \
                --distpath dist_intel \
                --workpath build_intel \
                $GITHUB_WORKSPACE/ACN_x86_64.spec
            else
              python -m PyInstaller --clean \
                --distpath dist \
                --workpath build \
                $GITHUB_WORKSPACE/ACN_arm64.spec
            fi

            if [ "${{ matrix.arch }}" = "x86_64" ]; then
            hdiutil create \
              -volname "ACN Backtester" \
              -srcfolder dist_intel/ACN\ Backtester.app \
              -ov -format UDZO \
              ACN-Backtester-x86_64.dmg
            mv ACN-Backtester-x86_64.dmg $GITHUB_WORKSPACE
            else
              hdiutil create \
                -volname "ACN Backtester" \
                -srcfolder dist/ACN\ Backtester.app \
                -ov -format UDZO \
                ACN-Backtester-arm64.dmg
              mv ACN-Backtester-arm64.dmg $GITHUB_WORKSPACE
            fi
          
      - name: Publish Release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ACN-Backtester-arm64.dmg
            ACN-Backtester-x86_64.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}