name: Build & Publish DMGs via Spec

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write

jobs:
  build-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: arm64

      - name: Build & package arm64
        shell: bash
        run: |
          TMP=$(mktemp -d)
          cd "$TMP"

          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip pyinstaller numpy
          pip install -r requirements.txt

          python -m PyInstaller --clean \
            --distpath dist \
            --workpath build \
            "$GITHUB_WORKSPACE/ACN_arm64.spec"

          hdiutil create \
            -volname "ACN Backtester" \
            -srcfolder "dist/ACN Backtester.app" \
            -ov -format UDZO \
            ACN-Backtester-arm64.dmg

          mv ACN-Backtester-arm64.dmg "$GITHUB_WORKSPACE"

      - uses: actions/upload-artifact@v4
        with:
          name: dmg-arm64
          path: ACN-Backtester-arm64.dmg

  build-x86:
    runs-on: macos-latest
    needs: build-arm64
    steps:
      - uses: actions/checkout@v3

      - name: Install Rosetta
        run: softwareupdate --install-rosetta --agree-to-license

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: x64

      - name: Build & package x86_64
        shell: bash
        run: |
          TMP=$(mktemp -d)
          cd "$TMP"

          arch -x86_64 python -m venv venv
          source venv/bin/activate
          arch -x86_64 pip install --upgrade pip pyinstaller numpy
          pip install -r requirements.txt

          arch -x86_64 python -m PyInstaller --clean \
            --distpath dist_intel \
            --workpath build_intel \
            "$GITHUB_WORKSPACE/ACN_x86_64.spec"

          arch -x86_64 hdiutil create \
            -volname "ACN Backtester" \
            -srcfolder "dist_intel/ACN Backtester.app" \
            -ov -format UDZO \
            ACN-Backtester-x86_64.dmg

          mv ACN-Backtester-x86_64.dmg "$GITHUB_WORKSPACE"

      - uses: actions/upload-artifact@v4
        with:
          name: dmg-x86_64
          path: ACN-Backtester-x86_64.dmg

  release:
    runs-on: ubuntu-latest
    needs: [build-arm64, build-x86]
    steps:
      - uses: actions/download-artifact@v4
        with: { name: dmg-arm64 }
      - uses: actions/download-artifact@v4
        with: { name: dmg-x86_64 }

      - name: Publish Release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ACN-Backtester-arm64.dmg
            ACN-Backtester-x86_64.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}