name: Build & Publish DMGs via Spec

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64, x86_64]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Rosetta (for Intel)
        if: matrix.arch == 'x86_64'
        run: softwareupdate --install-rosetta --agree-to-license

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: ${{ matrix.arch == 'x86_64' && 'x64' || 'arm64' }}

      - name: Prepare & build
        run: |
          # create & activate arch-specific venv
          python -m venv .venv-${{ matrix.arch }}
          source .venv-${{ matrix.arch }}/bin/activate
          pip install --upgrade pip
          pip install --upgrade pyinstaller
          pip install -r requirements.txt 

          # copy source out of numpy namespace
          mkdir build && rsync -a --exclude .git --exclude .venv ./ build/src
          cd build/src

          # build app
          if [ "${{ matrix.arch }}" = "x86_64" ]; then
            arch -x86_64 python -m PyInstaller --clean \
              --distpath dist_intel \
              --workpath build_intel \
              ACN_x86_64.spec 
          else
            pyinstaller --clean ACN_arm64.spec
          fi

          # package DMG
          DMG="ACN-Backtester-${{ matrix.arch }}.dmg"
          if [ "${{ matrix.arch }}" = "x86_64" ]; then
            arch -x86_64 hdiutil create -volname "ACN Backtester" \
              -srcfolder "dist/ACN Backtester.app" -ov -format UDZO "${DMG}"
          else
            hdiutil create -volname "ACN Backtester" \
              -srcfolder "dist/ACN Backtester.app" -ov -format UDZO "${DMG}"
          fi

          # move artifact to workspace root
          mv "${DMG}" $GITHUB_WORKSPACE

      - name: Publish Release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ACN-Backtester-arm64.dmg
            ACN-Backtester-x86_64.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}